name: Flutter CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Get Latest Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: Get Previous Commit SHA
        run: echo "PREVIOUS_COMMIT_SHA=$(git rev-parse HEAD^)" >> $GITHUB_ENV
        
      - name: Check for Changes in Code
        run: echo "CODE_CHANGED=$(git diff --name-only $PREVIOUS_COMMIT_SHA $COMMIT_SHA)" >> $GITHUB_ENV
        
      - name: Determine Version Increment
        run: |
          if [ -n "$CODE_CHANGED" ]; then
            echo "VERSION_INCREMENT=patch" >> $GITHUB_ENV # Assuming a patch version increment for simplicity
          else
            echo "VERSION_INCREMENT=none" >> $GITHUB_ENV
          fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        if: success() && env.VERSION_INCREMENT != 'none'
        uses: actions/upload-artifact@v2
        with:
          name: my-apk
          path: build/app/outputs/flutter-apk/app-release.apk
