name: Get Release Version

on:
  workflow_dispatch:
  
jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
    - name: Display Version
      run: echo "The released version is ${{ github.event.release.tag_name }}"

  get_version2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Get Latest Tag
      id: get_tag
      run: |
        echo ::set-output name=TAG::$(git describe --tags --abbrev=0)
    - name: Display Version
      run: echo "The released version is ${{ steps.get_tag.outputs.TAG }}"

    - name: Get Latest Release
      id: get_latest_release
      uses: actions/github-script@v6
      with:
        script: |
          const { data: release } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          core.setOutput('version', release.tag_name);
    - name: Display Version
      run: echo "The released version is ${{ steps.get_latest_release.outputs.version }}"
